# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - master
    - refs/tags/*
  paths:
    exclude:
      - README.md

pool:
  vmImage: 'Ubuntu-16.04'

variables:
- group: Default

steps:
- task: Bash@3
  inputs:
    filePath: './build.sh'
    arguments: '--target Clean --skip'
  displayName: 'Run the Clean target'
- bash:
    filePath: './build.sh'
    arguments: '--target ExportGitVersion --skip'
  displayName: 'Run the ExportGitVersion target'
- bash: |
    echo "##vso[build.updatebuildnumber]${GitVersion_NuGetVersionV2}_${BUILD_BUILDNUMBER}"
  displayName: 'Set build number'
- task: Bash@3
  inputs:
    filePath: './build.sh'
    arguments: '--target Restore --skip'
  displayName: 'Run the Restore target'
- task: Bash@3
  inputs:
    filePath: './build.sh'
    arguments: '--target Package --skip'
  displayName: 'Run the Package target'
- task: Bash@3
  inputs:
    filePath: './build.sh'
    arguments: '--target Publish --skip --nuget-api-key $(NUGETAPIKEY)'
  displayName: 'Run the Publish target'
